# Generated by Django 5.1.4 on 2025-01-16 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_medicine_created_at_medicine_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='inventory.category'),
        ),
    ]
